version: 2.1

orbs:
  node: circleci/node@3.0.1

jobs:
  publish:
    executor: node/default
    steps:
      - checkout
      - run: yarn install
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run: npm publish

workflows:
  main:
    jobs:
      - publish:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v([0-9]+).([0-9]+).([0-9]+)$/
